### ISSUE TITLE
documentation inconsistency

### ISSUE THREAD

**Issue by melanger** [IdentityPython/oidc-op#142]
In many tests and examples, including the [main example](https://github.com/IdentityPython/oidc-op/blob/a87177e7a5d0b40dcff11ed75b39a72bd2d3f015/docs/source/contents/conf.rst), the configuration option for claims is written as `add_claim_by_scope` (singular `claim`), but in the source code, it is `add_claims_by_scope` (plular `claims`):

https://github.com/IdentityPython/oidc-op/blob/a87177e7a5d0b40dcff11ed75b39a72bd2d3f015/src/oidcop/session/claims.py#L28

https://github.com/IdentityPython/oidc-op/blob/a87177e7a5d0b40dcff11ed75b39a72bd2d3f015/src/oidcop/oidc/userinfo.py#L38

I guess the documentation and tests should be fixed to `add_claims_by_scope`.

**Comment by peppelinux** [comment]
Think you're right
@nsklikas can you confirm this?

@melanger feel free to put your contribution with a Pull Request, thank you
