### ISSUE TITLE
disable weak algorithms

### ISSUE THREAD

**Issue by peppelinux** [IdentityPython/oidc-op#22]
The following algorithms must be disabled by default:

- RSA1_5
- none

**Comment by peppelinux** [comment]
reference
https://tools.ietf.org/html/rfc8725

**Comment by rohe** [comment]
OK

**Comment by peppelinux** [comment]
in https://github.com/IdentityPython/oidc-op/pull/38 I found a good compromise

the weak algs doesn't been disabled by default but a warning message raises if there are found in the configuration
