### ISSUE TITLE
default_claims

### ISSUE THREAD

**Issue by peppelinux** [IdentityPython/oidc-op#28]
The example configuration provided in flask_op have 

````
      "id_token": {
        "class": "oidcop.id_token.IDToken",
        "kwargs": {
          "default_claims": {
            "email": {
              "essential": true
            },
            "email_verified": {
              "essential": true
            }
          }
        }
      },
````

I can't figure out how the attribute default_claims is involved in operations, can't find it in the source tree neither in unit tests.
To issue some custom claims in IDToken I made this changements

````
    "class": "oidcop.id_token.IDToken",
    "kwargs": {
        "base_claims": {
            "email": None,
            "email_verified": None,
        },
    },
````

the same for Token handler

````
"token": {
      "class": "oidcop.token.jwt_token.JWTToken",
      "kwargs": {
        "lifetime": 3600,
        # this will add email in access_token
        "base_claims": {
            "email": None,
            "email_verified": None,
        }
      }
    },
````

**Comment by rohe** [comment]
It's supposed to be `base_claims` and it's handled in oidcop.session.claims.ClaimsInterface.get_claims().
`default_claims` was an earlier name.

**Comment by peppelinux** [comment]
Ok, so I can self assign to update documentation and configuration example
