### ISSUE TITLE
access token claims

### ISSUE THREAD

**Issue by peppelinux** [IdentityPython/oidc-op#34]
Here an example of an access_token issued by oidc-op develop branch.

@rohe Shouldn't we use also **jti** and **sub** in it? See [bertocci-oauth-access-token-jwt](https://tools.ietf.org/id/draft-bertocci-oauth-access-token-jwt-00.html#rfc.section.2.2)

the following claims in bold would be those we could consider to include:

**Access Token**

 {
  "scope": [
    "openid",
    "profile",
    "email",
    "address",
    "phone"
  ],
  "aud": [
    "zwo0ucVvDuvbS-gcozbO3A"
  ],
  "sid": "Z0FBQUFBQmdubHJJSDh0TEFsc1UtWmlTWnlmVGw5NnpXbm96aTU2NEF1dmFNaWhqMlVtVkdJVUllVjFEbnBaTi04c2xrU3pOaXZVYWpmRC1TeExfVWRWY2tfY3pCV1N3X0NGbUp0all5WG41VmdvLXpxWUk3WFBZMGROOTBKZldTaGNibEhqcVZqZVFIdzc5dlg5ZlJQRnNIbWpOOVdSZnk2SHY2eUNoQ1U5cVhBMjZjMGxOcGRZbVA1TEE3X3FNRHoyWFlUTEdKcjVVTnBQV0p2SUtPY1l2SlFQbVc2aDhQUzlHZW94Smt4bDl6UDRHNmpwT0hXST0=",
  "ttype": "T",
  "iss": "https://127.0.0.1:8000",
  "iat": 1620990664,
  "exp": 1620994264,
 
  **"sub"**: "zwo0ucVvDuvbS-gcozbO3A", # issued to this client, that's the subject
  **"client_id"**: "zwo0ucVvDuvbS-gcozbO3A", # yes ... again?
  **"jti"**: df8a90s8df90asfas-asdf8asdf-adsf89sdfsdfsa-sda089f7as89f798sd7f
}

Is there a customization to introduce any additional claim, static or dynamic, in the global configuration?
that would be great for documentation

**Comment by rohe** [comment]
Agree that we should add sub, client and jti.
Regarding adding other claims we have the possibility to add user claims. No way to add other claims.

You can do things like this:

**Comment by peppelinux** [comment]
Otherwise I should inherit `oidcop.token.jwt_token.JWTToken` and put my class in the global conf, I'm wondering ...
