### ISSUE TITLE
Missing TokenIntrospection in examples project

### ISSUE THREAD

**Issue by peppelinux** [IdentityPython/oidc-op#47]
It would be better to have it :)

**Comment by rohe** [comment]
example/flask_op do have an introspection endpoint.
Don't know which example project you are talking about.

**Comment by peppelinux** [comment]
The same but I miss It, my excuses 😎

**Comment by peppelinux** [comment]
done here:
https://github.com/IdentityPython/oidc-op/pull/59/commits/4286cc8a9d76c4da094ea756a9c9ecb1897ca84e
