### ISSUE TITLE
[Documentation] Pairwise salt

### ISSUE THREAD

**Issue by peppelinux** [IdentityPython/oidc-op#50]
the salt involved in subject must be documented, otherwise it's hard to go in production with multiple workers that have random salt in each of their instances

see `oidcop.session.manager.PairWiseID` and other IDs

**Comment by rohe** [comment]
Salt is defined as a dump parameter in SessionManager. It should take care of this.
May have to add a test to verify it.

**Comment by peppelinux** [comment]
it seems to me that's not actually aware of it

````
      },
      "session_key": {
        "filename": f"{OIDC_JWKS_PRIVATE_PATH}/session_jwk.json",
        "type": "OCT",
        "use": "sig"
      },
      "sub_func": {
        "public": {
          "class": "oidcop.session.manager.PublicID",
          "kwargs": {
            "salt": "sdfsdfdsf"
          }
        },
        "pairwise": {
          "class": "oidcop.session.manager.PairWiseID",
          "kwargs": {
            "salt": "sdfsdfsdf"
          }
        }
     },
 ````
 
 the dump shows random salt instead of the defined one

**Comment by peppelinux** [comment]
and more, it happens, somethimes, that session manager dump doesn't have salt and key correctly valued

````
...

 'id_token'], 'max_usage': 1}, 'used': 0, 'claims': {}, 'id': '5c0b3dc9b71b11eb83cf558fb4b9e83d', 'name': 'AuthorizationCode', 'resources': [], 'scope': [], 'type': 'authorization_code', 'value': 'Z0FBQUFBQmdvbnc2bFJua3RBQWFFM0x5ZnBhTVlKdFROb0hna1ROZFpkOWhSNlJxdEw4RldYQ0szSkVCREhOaGJLUFVteExVb2tuZzd3SjRHY2Nlb2k2a0FKQTRDbWxjWENJdkFXMHNlLTNXOHkyUUhlZ0d1d2RyR29MT3NNcDQxdms3cHp6WW1PYW9PWm50OUVPVGFOUmU5Ym42bWIya2ZKQVhaekFhR09sN3RoT1JhMmRjbDNjdDR4WW8zMFFaN2phaERVdjBDanZqQ2RFS0kyNWtnb3kwUFJxRTJTcEx0ZTZuRkhMNlYxZXN3NjJiUl83RVk4bkpTc1lkejctbEFoZ3NlekpDb3JEOTVNSnlmNXg5TGJCSHFjSmMzb09CaWxQdU42dEtNWmNRWVJqQUN1WFlwc2Rnb2Vzb0luMDNwTVRPM0w1V2JOXzJqNDNSRnJTdE9DdDhVLWJqYURtRklhTWZSd09YWm4yY2ZwUUNwSHZHUTAwZEUzWGpWdG9DQi1tTTg1cmJjdGNqdmR6ODdfbEtycldOb2JJVWVvRWlYZ0xSVGxMWXNybW1Fcm9fem1DQ0RQZ2VFalFsRmJOSWRhVlBWUE90UUFydUE4Rm1hQWVUMTFVNDNqOEkydzNlQldsRld5aG9KNUtBSnVUbm5kQlpaei1WT2Itd3RPVHJJRzhJSS1WOENXSlBTVUxmbE9keFFQVmU4MDZOY3dYVVl5TUxlMDQ2RGtxT3F4X01qNWtQcExhY3RrM3A2VDFrYjd3a2FSTzVwdV9BU014MUtTZ01GelRDMlRLN2xTRHNXTC1sUEZZSGc4bEhlOGtOUlFXSlZSND0='}}], 'token_map': {'authorization_code': 'oidcop.session.token.AuthorizationCode', 'access_token': 'oidcop.session.token.AccessToken', 'refresh_token': 'oidcop.session.token.RefreshToken', 'id_token': 'oidcop.session.token.IDToken'}}]}, 'key': '', 'salt': ''}

````

**Comment by rohe** [comment]
Ah, now I get it. 

Each sub function doesn't have a salt of its own the SessionManager instance has a salt which is then used by all sub function.

**Comment by peppelinux** [comment]
Ok, how to deal with that?
Do you have something to be coded/refactored in the project or do we have to made some changes in documentation and example configuration?

**Comment by rohe** [comment]
I think changing documentation and example configuration is what should be done.

**Comment by peppelinux** [comment]
Put your notes here, I can do the commit or do your commits then I'll updated the pendig PR about the Docs

**Comment by rohe** [comment]
I don't think there is anything to change in the example/flask_op configuration.
And there is no mentioning of salt in the documentation that I can find.

**Comment by peppelinux** [comment]
The missing salt was fixed here
https://github.com/IdentityPython/oidc-op/pull/59

This issue wants to do some docs about sub_funcs and salt. Now I see how this salt have been involved in session manager, it's time for documenti It!

**Comment by peppelinux** [comment]
Closed by https://github.com/IdentityPython/oidc-op/pull/59
