### ISSUE TITLE
Invalid token_type SessionToken

### ISSUE THREAD

**Issue by nsklikas** [IdentityPython/oidc-op#55]
The `token_type` in the `SessionToken` describes the class of the token (`access_token`, `refresh_token`, ...).

In the OAuth2 spec token_type is used to describe an access_token(https://datatracker.ietf.org/doc/html/rfc6749#section-7.1)

`token.token_type` is used in the introspection endpoint to get the value of the token_type(https://github.com/IdentityPython/oidc-op/blob/develop/src/oidcop/oauth2/introspection.py#L47), which is wrong (it shouldn't be `access_token`, but `Bearer`)

We had this discussion on slack some time ago, I am going to try to document our decision so that we can move forward with implementing it.
We are going to have the following toke fields: `token_type`, `token_syntax`, `token_class`:
- `token_type`: will be used only for access_tokens, the possible values will be `bearer` and `mac` according to https://datatracker.ietf.org/doc/html/rfc6749#section-7.1 
- `token_syntax`: will describe the syntax of the token  like `JWT`, `SAML1`, `SAML2` according to https://datatracker.ietf.org/doc/html/rfc8693#section-3. Perhaps we should add the value `STRING` for random string tokens?
- `token_class`: The class of the token (the current `token_type`), this will take one of the following values: `authorization_code`, `access_token`, `refresh_token`, `id_token`.

@rohe @peppelinux what do you think? Should we start implementing this?

**Comment by rohe** [comment]
Absolutely !!!

**Comment by rohe** [comment]
There is a third token_type we can add 'DPoP'.

Doesn't change the overall design.

And yes we probably need something like `string` or `undefined`.

I assume `token_class` is a reference to the class of the token not the name of the class which should be in Camelback.

**Comment by peppelinux** [comment]
it's great @nsklikas , make order and clarity, I'm really happy you realized this before the upcoming release

**Comment by peppelinux** [comment]
@rohe I put this issue in the v2.0 milestone, do you agree that this can be handled in it or do you prefer to create a 2.0.1 milestore for this?

**Comment by rohe** [comment]
I think it's a good idea to do it as part of 2.0.0 .

**Comment by rohe** [comment]
I can start taking a stab at this later today if no one else feels like taking it on.

**Comment by nsklikas** [comment]
I haven't had the time yet, you can start it if you want and I can jump in later

Thanks

**Comment by rohe** [comment]
Working on it!

**Comment by rohe** [comment]
Branch token_type. First walk through.

**Comment by rohe** [comment]
Implemented in #74
