### ISSUE TITLE
seed, password and salt. Semantically exiled and far from home

### ISSUE THREAD

**Issue by peppelinux** [IdentityPython/oidc-op#60]
we have these three "root" parameters in OPConfiguration: seed, password and salt, and these, sooner or later, will have to be documented.

seed is only involved in client secret creation.
password and salt are involved, @rohe correct me if I'm wrong, in session storage.

I think that we should do a refactor and rename/move these parameters in some other section or give to them a better semantic.
We have `session_key` section and also the sub_funcs ... should they belongs to a Session section to get them all in?

 and also "seed", shouldn't it be better to move to registration endpoint paramenters?

**Comment by peppelinux** [comment]
Actually we have

````
  "op": {
    "server_info": {
      # "seed": "CHANGE-THIS-RANDOMNESS!!!",
      "password": 'password_used_to_encrypt_access_token_sid_value',
      "salt": "salt involved in session sub hash ",
      "session_key": {
        "filename": "private/session_jwk.json",
        "type": "OCT",
        "use": "sig"
      },
      "sub_func": {
        "public": {
          "class": "oidcop.session.manager.PublicID",
          "kwargs": {
            "filename": "public.salt"
          }
        },
        "pairwise": {
          "class": "oidcop.session.manager.PairWiseID",
          "kwargs": {
            "filename": "pairwise.salt"
          }
        }
````

password, salt, session_key and sub_funcs all are related to session manager.
Here a proposal


````
"op": {
    "server_info": {
        "session_manager": {
          "password": 'password_used_to_encrypt_access_token_sid_value',
          "salt": "salt involved in session sub hash ",
          "session_key": {
            "filename": "private/session_jwk.json",
            "type": "OCT",
            "use": "sig"
          },
          "sub_func": {
            "public": {
              "class": "oidcop.session.manager.PublicID",
              "kwargs": {
                "filename": "public.salt"
              }
            },
            "pairwise": {
              "class": "oidcop.session.manager.PairWiseID",
                  "kwargs": {
                    "filename": "pairwise.salt"
                  }
              }
           }
        }
    }
}
````

**Comment by rohe** [comment]
OK, LGTM.

**Comment by rohe** [comment]
Actually, it might be that session_key is an historical artefact and can therefor be removed.

**Comment by peppelinux** [comment]
Do we think to have this to 2.0.0 roadmap?
It Will be a breaking change because it's at the base of the configuration schema

**Comment by rohe** [comment]
We can have it in the 2.1.0 road map.

**Comment by peppelinux** [comment]
closed by https://github.com/IdentityPython/oidc-op/pull/72
