### ISSUE TITLE
ID Token introspection

### ISSUE THREAD

**Issue by nsklikas** [IdentityPython/oidc-op#78]
Currently providing an ID Token to the introspection endpoint results in an unhandled exception.

@rohe @peppelinux What are out plans regarding using ID tokens in the introspection endpoint? 
IMO we should allow introspection of ID tokens.

**Comment by peppelinux** [comment]
@nsklikas I think that an unhandled exception means a bug 😀 

Put a unit test for this of you can, then we'll see what's going on.

I'm quite sure that an IDToken would be handled by token introspection, and more... Every issues token should be handled. Probably you face a bug, let's patch It!

**Comment by peppelinux** [comment]
Do you tested on this
https://github.com/IdentityPython/oidc-op/pull/74
?

**Comment by rohe** [comment]
There is no support for introspection of ID Tokens at the introspection endpoint and there shouldn't be.
But it shouldn't result in an unhandled exception.

**Comment by peppelinux** [comment]
If @nsklikas desire this feature in, let's give him a chance

It's quite trivial to get that information from a session Grant

That's something for 2.1.0 if you agree, @nsklikas  would you go ahead in the meantime?

**Comment by rohe** [comment]
It's not that simple. 
Remember that introspection is a OAuth2 functionality and not OIDC. And that ID Tokens is an OIDC addition.
Introspection was invented because access tokens where supposed to be non-readable to the user.
ID Tokens are by definition readable by anyone and not supposed to be used as access tokens.

**Comment by peppelinux** [comment]
This meant that @nsklikas would have a oidc aware token introspection endpoint?

The Sky Is the limit 😎

Regarding the nature of the endpoint, yes I agree that belongs to oauth2 but @nsklikas how would you del with this?

**Comment by nsklikas** [comment]
Many providers out there support the introspection of ID Tokens. It's true that it's an OAuth2 endpoint and I don't know if we should support it as well.

I guess it would make sense to introspect encrypted ID Tokens (the client may not have the encryption key).

The reason it fails is that `get_session_info_by_token` expects to find the `session_id` in the token, but ID Tokens don't contain the session_id.
